# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingester', '0019_auto_20170501_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.IntegerField()),
                ('source_key', models.CharField(db_index=True, max_length=150)),
                ('ingester_key', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingester.local_url')),
            ],
        ),
        migrations.CreateModel(
            name='PDFDownloadQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tries', models.IntegerField(default=0)),
                ('last_try', models.DateTimeField(blank=True, default=None, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weaver.OpenReferences')),
            ],
        ),
        migrations.CreateModel(
            name='PubReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingester.cluster')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingester.local_url')),
            ],
        ),
        migrations.CreateModel(
            name='SingleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=None, null=True)),
                ('authors', models.BinaryField()),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('INC', 'INCOMPLETE'), ('LIM', 'LIMBO'), ('FIN', 'FINISHED')], default='OP', max_length=3)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaver.OpenReferences')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pdfdownloadqueue',
            unique_together=set([('url', 'source')]),
        ),
    ]
